[workspace]
authors = ["João Vítor Carli Pereira <jvitor.carli@gmail.com>"]
channels = ["conda-forge"]
name = "chore-adiciona-template"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
typst = ">=0.14.2,<0.15"

[feature.dev.dependencies]
just = ">=1.47.0,<2"
python = ">=3.14.3,<3.15"

[feature.docs.dependencies]
mdbook = "==0.5.2"

[environments]
default = { features = ["dev", "docs"] }
