[[repos]]
repo = "local"
hooks = [
  {
    id = "check-typst-examples",
    name = "Check if Typst examples compile",
    language = "system",
    entry = "python scripts/check_typst_examples.py",
    files = '\.typ$|typst\.toml',
    pass_filenames = false,
  },
]
